### ISSUE TITLE
feature request: confirm team member response in slack integration

### ISSUE THREAD

**Issue by chadlavi** [supportkit/supportkit-js#113]
Supportkit posts "`person` started a conversation in `#sk-channel-name`" in the channel you've selected in slack. It would be great if supportkit posted "`teamMember` replied in `#sk-channel-name`" the first time a member of your team posted using the `/sk` command in the channel `#sk-channel-name`, so that the channel where supportkit posts new channel links shows clearly whether or not a conversation has been followed up on.

**Comment by lemieux** [comment]
Hey @chadlavi,

this is a great suggestion and I'll add it on our review list. I understand completely the use case and I can see how useful this could be.

I'll close the issue here since it doesn't concern the web widget, but be sure we'll discuss that for a future release.

Thanks!

**Comment by chadlavi** [comment]
Thanks @lemieux!
