### ISSUE TITLE
embeddedMode not working

### ISSUE THREAD

**Issue by acharyasarvesh** [supportkit/supportkit-js#114]
I have specified embeddedMode to true with specification of container with class name. Rather its rendered as a window only.

**Comment by lemieux** [comment]
Hey @acharyasarvesh ,

did you use this branch https://github.com/lemieux/supportkit-js/tree/f/embedded-mode for the embedded mode? This mode is not a supported feature of the official SupportKit SDK, but a feature I added in my personnal fork of it.

**Comment by acharyasarvesh** [comment]
I included the link as you have also mentioned to include the cdn link for this.

**Comment by lemieux** [comment]
Oh that's my bad then! You'll need to clone the repo and build the package yourself. I forgot to remove the cdn mention in the readme.

**Comment by acharyasarvesh** [comment]
Ok thanks
