### ISSUE TITLE
Documentation incorrect for bower

### ISSUE THREAD

**Issue by Sk1Zy** [supportkit/supportkit-js#31]
http://docs.supportkit.io/javascript/#script-tag-method

It says the package name is supportkit-js when it's name is just supportkit.

So it should say bower install supportkit

**Comment by lemieux** [comment]
Hey @Sk1Zy ,

you are right and this is a complete oversight on our side. We decide at the last minute to use supportkit instead of supportkit-js when we made the packages available.

I'll make sure this is updated!
