### ISSUE TITLE
Text wraps mid-word in FF 39.0 and IE10 in chat window

### ISSUE THREAD

**Issue by johann-abraham** [supportkit/supportkit-js#49]
in the following screenshot see the words message, and to.  For message the 'e' wraps to the next line.  For to, the 'o' wraps to the next line. 

![screen shot 2015-07-23 at 4 51 57 pm](https://cloud.githubusercontent.com/assets/2205178/8861984/76f3de66-315b-11e5-96b8-1ed06f80b24c.png)

Screen shot for IE 10
![screen shot 2015-07-23 at 4](https://cloud.githubusercontent.com/assets/2205178/8862163/90f4cb26-315c-11e5-95b0-e60366456ea8.png)

This is not a problem in Chrome.

**Comment by lemieux** [comment]
Hey Johann! 

Thanks for reporting this,  I'll make sure to take a look at it first thing tomorrow morning. Seems like that slipped through our cross browser tests. 

I'll keep you posted.

**Comment by johann-abraham** [comment]
thanks @lemieux

**Comment by lemieux** [comment]
@johann-abraham the fix should be live in a few minutes.

Thanks again!
