### ISSUE TITLE
SupportKit.updateUser doesn't work

### ISSUE THREAD

**Issue by pranavguptarulz** [supportkit/supportkit-js#53]
We at [razorpay](https://razorpay.com) are relying on `SupportKit.updateUser` for adding email and contact info. But this doesn't seem to work since last release.

`SupportKit.user.set('email', 'foo@bar.com')` followed by `SupportKit.user.save()` is working though, and we're falling back to it for now.

**Comment by pranavguptarulz** [comment]
opened a request https://github.com/supportkit/supportkit-js/pull/54

Issue seems to be failing `user.isDirty()`, because user is not updated with new attributes during whole process at all.

**Comment by lemieux** [comment]
Hey @pranavguptarulz, we should be merging #48 real soon and it should fix that problem.

Thanks for reporting this!

**Comment by pranavguptarulz** [comment]
@lemieux good to know.
