### ISSUE TITLE
Email capture additions

### ISSUE THREAD

**Issue by ahansson89** [supportkit/supportkit-js#72]
I would love to see an option for forcing people to leave their email before being able to send message something like:

emailCaptureRequired: true

And maybe an option to have the email view open when doing SupportKit.Open(), but not require the email field to be filled: 

emailCaptureOnOpen: true

**Comment by jpjoyal** [comment]
I understand the two setting. SupportKit really wants you to have a conversation with your users. Personally as a user I prefer starting the conversation before having to enter my email.. I understand the appMaker's perspective where grabbing the email is the most important thing though. We feel like having the email form first is intimidating and might turn people off.

Can you elaborate on why it's more important to you to get the email of the user versus maximizing the feedback you get from users ?

Also, to understand better, in your use case, there's no way for you to feed the user email to the SupportKit api?

**Comment by ahansson89** [comment]
We are using it as a live chat feature, which I imagine that our customers would use mostly for pre-sales questions. For this reason, we do not have any data on the user yet and it is therefore an awesome way to get the email address on the user. For this reason I could also see a potential for a MailChimp integration being added later.

Also as there is no way for us to check if an active individual available on Slack, we would like to get back to the customer on email if we are not available 24/7. Potentially you are limiting small teams from using your service if they are not available 24/7.

For every email input field we have on our site we can send the data to the SupportKit API, but it does not give us the ability to capture the lead data if they want to chat about our service before subscribing if they have not signed up for our newsletter for example.

**Comment by ahansson89** [comment]
Also instead of only saving the email data in the Settings screen, the save button should close the settings again so that the user can start interacting with the vendor. Right now the user needs to save settings, then click the back button.

**Comment by lemieux** [comment]
Hey @ahansson89, 

thanks for your feedback about the save button, we changed that behavior for the release (it should roll out today). As for the ability of having the email form opened first, we put that in our discussion board, but  currently we feel it's a better experience to let the user initiate the conversation and ask for their email afterwards. We think it should trigger more conversations than if we ask for the email first.

I'll close this issue once we roll out the next release since it fixes the behavior you reported and we will discuss your suggestion.

Thanks again :)

**Comment by pudgereyem** [comment]
Hey @ahansson89,
this is how I added "Email Capture Addon"; https://gist.github.com/pudgereyem/d9647afcac841149e484 – if that may help you.
