### ISSUE TITLE
FontAwesome dependency not downloading with npm

### ISSUE THREAD

**Issue by Predjo** [supportkit/supportkit-js#79]
After doing `npm install`on a 0.2.24 version all dependencies download except for font awesome. Which causes build problems.

```
supportkit@0.2.24 node_modules/supportkit
├── cookie@0.1.3
├── url-join@0.0.1
├── view-controller@1.0.4
├── marionette.behaviors@0.0.13
├── uuid@2.0.1
├── underscore@1.8.3
├── backbone@1.2.1
├── backbone.stickit@0.9.2
├── backbone-computedfields@0.0.10 (underscore@1.5.2, backbone@1.1.2)
├── jquery@1.11.3
├── bootstrap@3.3.5
├── backbone-associations@0.6.2
├── urljoin@0.1.5 (extend@2.0.1)
├── backbone.marionette@2.4.2 (backbone.babysitter@0.1.8, backbone.wreqr@1.3.3)
├── lodash.bindall@3.1.0 (lodash.restparam@3.6.1, lodash._baseflatten@3.1.4, lodash._createwrapper@3.0.7, lodash.functions@3.0.0)
├── faye@1.1.2 (tunnel-agent@0.4.1, tough-cookie@2.0.0, csprng@0.1.1, faye-websocket@0.10.0)
├── jstify@0.7.0 (through2@0.6.5, html-minifier@0.6.9)
└── node-lessify@0.0.10 (object-assign@2.1.1, through2@0.6.5, less@2.4.0)```

**Comment by lemieux** [comment]
Did you have any errors in your log about it? I just tried to npm install supportkit and everything was good. Could it just be an npm problem?

**Comment by Predjo** [comment]
Nope no error whatsoever . If it helps node version 0.12.4 & npm version 2.13.4.

**Comment by lemieux** [comment]
Can you try removing supportkit from your node_modules and try it again? I have a hard time understanding why npm would not install font-awesome if it's in the dependencies and doesn't throw errors. Do you already have font-awesome in your project?

**Comment by Predjo** [comment]
Tried it, didn't help. And yes we use the font-awesome heavily.

**Comment by lemieux** [comment]
Is it in your npm dependencies?

**Comment by Predjo** [comment]
Yes

**Comment by lemieux** [comment]
What's your error on build?

**Comment by lemieux** [comment]
I'm pretty sure I figured it out. We are using relative path in our LESS files to generate the stylesheets, it probably breaks there since the font-awesome folder is not in supportkit node_modules level but at your app level.

**Comment by Predjo** [comment]
[Error: '../../node_modules/font-awesome/less/core.less' wasn't found.']
Yap that is probably it :+1:

**Comment by lemieux** [comment]
This is clearly a bug on our side. I'll put it on top of our todo list and keep you posted.

**Comment by lemieux** [comment]
Thanks :)

**Comment by lemieux** [comment]
@Predjo  0.2.25 should do the trick!

**Comment by Predjo** [comment]
Yap confirmed, thanks @lemieux  :+1:
